const offices = [{key:'house',label:'U.S. House',short:'House',sub:'435 districts'},{key:'senate',label:'U.S. Senate',short:'Senate',sub:'State contests'},{key:'governors',label:'Governors',short:'Governors',sub:'State executives'}];
const models = {
  special:{number:'01',title:'Special & off-year elections',short:'Observed vote',description:'Translate recent overperformance against prior baselines into a national electoral signal.',label:'Democratic overperformance',min:-5,max:5,step:.1,defaultValue:2.2},
  primary:{number:'02',title:'Primary election turnout',short:'Turnout intensity',description:'Use relative party participation to test enthusiasm and mobilization before November.',label:'Democratic turnout advantage',min:-5,max:5,step:.1,defaultValue:1.1},
  approval:{number:'03',title:'Presidential approval',short:'National climate',description:"Stress-test the historical relationship between approval and the president's party in a midterm.",label:'Presidential job approval',min:25,max:65,step:1,defaultValue:41},
  anes:{number:'04',title:'ANES panel studies',short:'Opinion movement',description:'Represent longitudinal coalition movement, issue salience, and partisan switching in the electorate.',label:'Net Democratic panel movement',min:-5,max:5,step:.1,defaultValue:1.3}
};
const modelOrder=['special','primary','approval','anes'];
const stateTiles=[["AK",1,1,-13],["ME",1,12,3],["WA",2,2,16],["ID",2,3,-28],["MT",2,4,-18],["ND",2,5,-34],["MN",2,6,7],["WI",2,7,1],["MI",2,8,2],["NY",2,10,13],["VT",2,11,25],["NH",2,12,4],["OR",3,2,12],["NV",3,3,0],["WY",3,4,-38],["SD",3,5,-29],["IA",3,6,-13],["IL",3,7,14],["IN",3,8,-19],["OH",3,9,-11],["PA",3,10,0],["NJ",3,11,7],["CT",3,12,13],["CA",4,2,20],["UT",4,3,-20],["CO",4,4,11],["NE",4,5,-20],["MO",4,6,-19],["KY",4,7,-25],["WV",4,8,-42],["VA",4,9,6],["MD",4,10,27],["DE",4,11,15],["RI",4,12,18],["AZ",5,3,0],["NM",5,4,10],["KS",5,5,-15],["AR",5,6,-30],["TN",5,7,-27],["NC",5,8,-1],["SC",5,9,-18],["MA",5,12,25],["HI",6,1,25],["TX",6,4,-14],["OK",6,5,-34],["LA",6,6,-22],["MS",6,7,-22],["AL",6,8,-27],["GA",6,9,-1],["FL",7,9,-13]];
const senateBallot=new Set(["AL","AK","AR","CO","DE","GA","ID","IL","IA","KS","KY","LA","ME","MA","MI","MN","MS","MT","NE","NH","NJ","NM","NC","OH","OK","OR","RI","SC","SD","TN","TX","VA","WV","WY"]);
const governorBallot=new Set(["AL","AK","AR","AZ","CA","CO","CT","FL","GA","HI","ID","IL","IA","KS","ME","MD","MA","MI","MN","NE","NV","NH","NM","NY","OH","OK","OR","PA","RI","SC","SD","TN","TX","VT","WI","WY"]);
const raceData={
  house:[['PA–07','Pennsylvania',49.6,.72],['NY–17','New York',49.1,.62],['AZ–06','Arizona',49.4,.78],['MI–07','Michigan',50,.69],['CA–13','California',49.3,.74],['NE–02','Nebraska',50.2,.58]],
  senate:[['Georgia','U.S. Senate',49.8,.68],['Michigan','U.S. Senate',50.1,.61],['North Carolina','U.S. Senate',49.4,.75],['Maine','U.S. Senate',49,.55],['Ohio','U.S. Senate',48.5,.7],['Texas','U.S. Senate',47.8,.66]],
  governors:[['Arizona','Governor',50.1,.7],['Michigan','Governor',49.9,.62],['Georgia','Governor',49.5,.72],['Nevada','Governor',50,.67],['Wisconsin','Governor',49.8,.74],['Kansas','Governor',48.8,.54]]
};
let office=document.body.dataset.office||'house';
let activeModel='special';
let values={special:2.2,primary:1.1,approval:41,anes:1.3};
const nested=document.body.dataset.nested==='true';
const home=nested?'../':'./';
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
const marginLabel=margin=>`${margin>=0?'D':'R'}+${Math.abs(margin).toFixed(1)}`;
const shift=()=>values.special*.34+values.primary*.24+(45-values.approval)*.14*.24+values.anes*.18;
const summary=()=>{const s=shift();if(office==='house'){const dem=clamp(Math.round(218+s*3.4),190,245);return{label:'Projected chamber',dem,gop:435-dem,total:435,threshold:'218 for control',title:'House delegation map',subtitle:'State tiles summarize the projected district delegation; the 435-seat matrix shows chamber control.'};}if(office==='senate'){const dem=clamp(Math.round(47+s*.8),45,53);return{label:'Projected chamber',dem,gop:100-dem,total:100,threshold:'51 for control',title:'2026 Senate map',subtitle:'States without a scheduled contest are muted. Active states respond to the four-model composite.'};}const dem=clamp(Math.round(17+s*.85),12,24);return{label:'Projected 2026 wins',dem,gop:36-dem,total:36,threshold:'36 scheduled races',title:'2026 governor map',subtitle:'Scheduled governor contests are colored by the prototype projected margin; other states are muted.'};};
const activeState=abbr=>office==='house'||(office==='senate'?senateBallot.has(abbr):governorBallot.has(abbr));

document.querySelector('#app').innerHTML=`
<a class="skip-link" href="#simulator">Skip to simulator</a><header class="site-header"><a class="brand" href="${home}" aria-label="RIPPL Election Simulator home"><span class="rippl-mark" aria-hidden="true"><i></i><i></i><i></i></span><span><strong>RIPPL</strong> Election Simulator</span></a><nav aria-label="Primary navigation"><a href="#simulator">Simulator</a><a href="#models">Four models</a><a href="#race-board">Race board</a><a href="#methodology">Methodology</a><a href="https://george-quinn.com/">George Quinn</a></nav></header>
<section class="masthead"><div class="masthead-grid" aria-hidden="true"></div><div class="masthead-copy"><p class="eyebrow"><span>2026 midterms</span> Research-informed political prediction lab</p><h1>Build the<br><em>national outcome.</em></h1><p>Test how four distinct electoral signals could reshape every House district, Senate contest, and governor race—then compare the map and the races that decide control.</p><a class="primary-action" href="#simulator">Start a simulation <span>↓</span></a></div><aside class="masthead-card"><div><span>Simulation structure</span><b>Prototype</b></div><strong>3 × 4</strong><p>Three nationwide race maps powered by four independently adjustable model lenses.</p><ul><li><span>01</span>Choose an office</li><li><span>02</span>Adjust the model signals</li><li><span>03</span>Read the map and race board</li></ul></aside></section>
<section class="office-switch" aria-label="Choose an office to simulate">${offices.map(item=>`<button type="button" data-office="${item.key}"><span>${item.short}</span><small>${item.sub}</small></button>`).join('')}</section>
<section class="simulator-section" id="simulator"><div class="section-intro"><div><p class="section-index">01 / Scenario lab</p><h2>Choose the signal.<br>Move the outcome.</h2></div><p>The controls below demonstrate the intended interaction. They use temporary weights and illustrative race baselines until the RIPPL models are formally specified and validated.</p></div><div class="prototype-notice"><strong>Interface prototype</strong><span>Displayed estimates are demonstrations of site behavior—not a published election forecast.</span></div><div class="simulator-grid"><aside class="model-rail" id="models"><div class="rail-head"><span>Four-model composite</span><button type="button" id="reset">Reset</button></div><div class="model-tabs">${modelOrder.map(key=>`<button type="button" data-model="${key}"><span class="model-number">${models[key].number}</span><span><strong>${models[key].title}</strong><small>${models[key].short}</small></span><b data-model-value="${key}"></b></button>`).join('')}</div><div class="active-control"><div class="active-control-title"><span id="edit-number"></span><strong id="edit-title"></strong></div><p id="edit-description"></p><label for="model-value"><span id="edit-label"></span><output id="edit-output"></output></label><input id="model-value" type="range"><div class="range-ends"><span id="range-min"></span><span id="range-max"></span></div></div><div class="composite-readout"><span>Prototype national environment</span><strong id="composite"></strong><small>Temporary composite · all four models included</small></div></aside><div class="output-stage" aria-live="polite"><div class="output-head"><div><p class="section-index">Nationwide output</p><h3 id="map-title"></h3><p id="map-subtitle"></p></div><div class="office-chip" id="office-chip"></div></div><div class="balance-panel"><div class="balance-copy"><span id="balance-label"></span><strong><span id="dem-total"></span><i>D</i></strong><b>to</b><strong><span id="gop-total"></span><i>R</i></strong><small id="threshold"></small></div><div class="balance-track"><span class="dem" id="dem-track"></span><span class="gop" id="gop-track"></span></div></div><div class="map-frame"><div class="state-map" id="state-map" role="img"></div><div class="map-legend" id="map-legend"></div></div><div class="district-matrix" id="district-matrix"></div></div></div></section>
<section class="race-section" id="race-board"><div class="section-intro compact"><div><p class="section-index">02 / Race board</p><h2>Where control<br>gets decided.</h2></div><p>The table updates with the four-model composite. Candidate names, polling, fundraising, and validated local effects can be connected during the model-building stage.</p></div><div class="race-table" id="race-table" role="table"></div></section>
<section class="methodology" id="methodology"><div><p class="section-index">03 / Build path</p><h2>From interface<br>to validated model.</h2><p>RIPPL will keep observed data, model assumptions, office-specific adjustments, and simulation uncertainty separate and visible.</p></div><ol><li><span>01</span><div><strong>Connect each data stream</strong><p>Define recency, geography, comparison baselines, missing-data rules, and update cadence.</p></div></li><li><span>02</span><div><strong>Estimate independent signals</strong><p>Prevent one noisy indicator from silently determining the entire national environment.</p></div></li><li><span>03</span><div><strong>Calibrate by office</strong><p>Translate the national signal differently for House districts, Senate contests, and governor races.</p></div></li><li><span>04</span><div><strong>Validate and simulate</strong><p>Back-test weights, propagate uncertainty, and publish race-level outputs with auditable assumptions.</p></div></li></ol></section>
<footer><div><a class="footer-brand" href="#top">RIPPL Election Simulator</a><p>Research-informed, transparent election scenarios by George D. Quinn.</p></div><div class="footer-links"><a href="#simulator">Simulator</a><a href="#models">Models</a><a href="#methodology">Methodology</a><a href="https://george-quinn.com/">Academic site</a></div><div class="footer-meta"><span>george-quinn.com</span><span>Prototype for the 2026 cycle</span></div></footer>`;

const update=()=>{
  document.querySelectorAll('[data-office]').forEach(button=>button.classList.toggle('active',button.dataset.office===office));
  document.querySelectorAll('[data-model]').forEach(button=>button.classList.toggle('active',button.dataset.model===activeModel));
  modelOrder.forEach(key=>document.querySelector(`[data-model-value="${key}"]`).textContent=key==='approval'?`${values[key].toFixed(0)}%`:marginLabel(values[key]));
  const definition=models[activeModel],slider=document.querySelector('#model-value');
  document.querySelector('#edit-number').textContent=`Editing model ${definition.number}`;document.querySelector('#edit-title').textContent=definition.title;document.querySelector('#edit-description').textContent=definition.description;document.querySelector('#edit-label').textContent=definition.label;document.querySelector('#edit-output').textContent=activeModel==='approval'?`${values[activeModel].toFixed(0)}%`:marginLabel(values[activeModel]);
  slider.min=definition.min;slider.max=definition.max;slider.step=definition.step;slider.value=values[activeModel];slider.style.setProperty('--range-progress',`${(values[activeModel]-definition.min)/(definition.max-definition.min)*100}%`);document.querySelector('#range-min').textContent=activeModel==='approval'?`${definition.min}%`:`R+${Math.abs(definition.min)}`;document.querySelector('#range-max').textContent=activeModel==='approval'?`${definition.max}%`:`D+${definition.max}`;document.querySelector('#composite').textContent=marginLabel(shift());
  const sum=summary();document.querySelector('#map-title').textContent=sum.title;document.querySelector('#map-subtitle').textContent=sum.subtitle;document.querySelector('#office-chip').textContent=offices.find(item=>item.key===office).label;document.querySelector('#balance-label').textContent=sum.label;document.querySelector('#dem-total').textContent=sum.dem;document.querySelector('#gop-total').textContent=sum.gop;document.querySelector('#threshold').textContent=sum.threshold;document.querySelector('#dem-track').style.width=`${sum.dem/sum.total*100}%`;document.querySelector('#gop-track').style.width=`${sum.gop/sum.total*100}%`;
  document.querySelector('#state-map').innerHTML=stateTiles.map(([abbr,row,col,base])=>{const active=activeState(abbr),adjusted=base+shift(),rating=!active?'not-up':adjusted>=12?'solid-d':adjusted>=4?'lean-d':adjusted>-4?'toss':adjusted>-12?'lean-r':'solid-r';return`<span class="${rating}" style="grid-row:${row};grid-column:${col}" title="${active?`${abbr}: ${marginLabel(adjusted)}`:`${abbr}: no scheduled contest`}">${abbr}</span>`;}).join('');
  document.querySelector('#map-legend').innerHTML=`<span><i class="solid-d"></i>Solid D</span><span><i class="lean-d"></i>Lean D</span><span><i class="toss"></i>Toss-up</span><span><i class="lean-r"></i>Lean R</span><span><i class="solid-r"></i>Solid R</span>${office==='house'?'':'<span><i class="not-up"></i>Not on ballot</span>'}`;
  document.querySelector('#district-matrix').innerHTML=office==='house'?`<div><span>435-seat matrix</span><b>Majority line: 218</b></div><div aria-hidden="true">${Array.from({length:435},(_,index)=>`<i class="${index<sum.dem?'dem':'gop'}"></i>`).join('')}</div>`:'';
  const races=raceData[office].map(([race,place,baseD,sensitivity])=>{const dem=clamp(baseD+shift()*sensitivity,35,64),gop=99-dem,margin=dem-gop;return{race,place,dem,gop,margin};}).sort((a,b)=>Math.abs(a.margin)-Math.abs(b.margin));
  document.querySelector('#race-table').innerHTML=`<div class="race-table-head"><span>Race</span><span>Projected vote</span><span>Margin</span><span>Rating</span></div>${races.map(race=>{const rating=Math.abs(race.margin)<1?'Toss-up':Math.abs(race.margin)<3?`Tilt ${race.margin>0?'D':'R'}`:`Lean ${race.margin>0?'D':'R'}`;return`<div class="race-row"><div><strong>${race.race}</strong><small>${race.place}</small></div><div class="vote-split"><span class="dem"><i style="width:${race.dem}%"></i>D ${race.dem.toFixed(1)}%</span><span class="gop"><i style="width:${race.gop}%"></i>R ${race.gop.toFixed(1)}%</span></div><strong class="${race.margin>=0?'dem-text':'gop-text'}">${marginLabel(race.margin)}</strong><span class="rating ${race.margin>=0?'dem-rating':'gop-rating'}">${rating}</span></div>`;}).join('')}`;
};
document.querySelectorAll('[data-office]').forEach(button=>button.addEventListener('click',()=>{office=button.dataset.office;update();}));document.querySelectorAll('[data-model]').forEach(button=>button.addEventListener('click',()=>{activeModel=button.dataset.model;update();}));document.querySelector('#model-value').addEventListener('input',event=>{values[activeModel]=Number(event.target.value);update();});document.querySelector('#reset').addEventListener('click',()=>{values={special:2.2,primary:1.1,approval:41,anes:1.3};update();});update();
